// Generated by gencpp from file prometheus_msgs/Case3Result.msg
// DO NOT EDIT!


#ifndef PROMETHEUS_MSGS_MESSAGE_CASE3RESULT_H
#define PROMETHEUS_MSGS_MESSAGE_CASE3RESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace prometheus_msgs
{
template <class ContainerAllocator>
struct Case3Result_
{
  typedef Case3Result_<ContainerAllocator> Type;

  Case3Result_()
    : header()
    , object_name(0)
    , score(0)  {
    }
  Case3Result_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , object_name(0)
    , score(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _object_name_type;
  _object_name_type object_name;

   typedef int32_t _score_type;
  _score_type score;





  typedef boost::shared_ptr< ::prometheus_msgs::Case3Result_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::prometheus_msgs::Case3Result_<ContainerAllocator> const> ConstPtr;

}; // struct Case3Result_

typedef ::prometheus_msgs::Case3Result_<std::allocator<void> > Case3Result;

typedef boost::shared_ptr< ::prometheus_msgs::Case3Result > Case3ResultPtr;
typedef boost::shared_ptr< ::prometheus_msgs::Case3Result const> Case3ResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::prometheus_msgs::Case3Result_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::prometheus_msgs::Case3Result_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::prometheus_msgs::Case3Result_<ContainerAllocator1> & lhs, const ::prometheus_msgs::Case3Result_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.object_name == rhs.object_name &&
    lhs.score == rhs.score;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::prometheus_msgs::Case3Result_<ContainerAllocator1> & lhs, const ::prometheus_msgs::Case3Result_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace prometheus_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::prometheus_msgs::Case3Result_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::prometheus_msgs::Case3Result_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::prometheus_msgs::Case3Result_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::prometheus_msgs::Case3Result_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::prometheus_msgs::Case3Result_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::prometheus_msgs::Case3Result_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::prometheus_msgs::Case3Result_<ContainerAllocator> >
{
  static const char* value()
  {
    return "92c5956f696ff8774f2e8961a1fc1b49";
  }

  static const char* value(const ::prometheus_msgs::Case3Result_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x92c5956f696ff877ULL;
  static const uint64_t static_value2 = 0x4f2e8961a1fc1b49ULL;
};

template<class ContainerAllocator>
struct DataType< ::prometheus_msgs::Case3Result_<ContainerAllocator> >
{
  static const char* value()
  {
    return "prometheus_msgs/Case3Result";
  }

  static const char* value(const ::prometheus_msgs::Case3Result_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::prometheus_msgs::Case3Result_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"## \n"
"int32 object_name\n"
"\n"
"## \n"
"int32 score\n"
"\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::prometheus_msgs::Case3Result_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::prometheus_msgs::Case3Result_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.object_name);
      stream.next(m.score);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Case3Result_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::prometheus_msgs::Case3Result_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::prometheus_msgs::Case3Result_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "object_name: ";
    Printer<int32_t>::stream(s, indent + "  ", v.object_name);
    s << indent << "score: ";
    Printer<int32_t>::stream(s, indent + "  ", v.score);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PROMETHEUS_MSGS_MESSAGE_CASE3RESULT_H
