// Generated by gencpp from file prometheus_msgs/Commitment.msg
// DO NOT EDIT!


#ifndef PROMETHEUS_MSGS_MESSAGE_COMMITMENT_H
#define PROMETHEUS_MSGS_MESSAGE_COMMITMENT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace prometheus_msgs
{
template <class ContainerAllocator>
struct Commitment_
{
  typedef Commitment_<ContainerAllocator> Type;

  Commitment_()
    : header()
    , uav_id(0)
    , commitmentState(0)
    , sitePos()
    , quality(0.0)  {
      sitePos.assign(0.0);
  }
  Commitment_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , uav_id(0)
    , commitmentState(0)
    , sitePos()
    , quality(0.0)  {
  (void)_alloc;
      sitePos.assign(0.0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _uav_id_type;
  _uav_id_type uav_id;

   typedef int32_t _commitmentState_type;
  _commitmentState_type commitmentState;

   typedef boost::array<float, 3>  _sitePos_type;
  _sitePos_type sitePos;

   typedef float _quality_type;
  _quality_type quality;





  typedef boost::shared_ptr< ::prometheus_msgs::Commitment_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::prometheus_msgs::Commitment_<ContainerAllocator> const> ConstPtr;

}; // struct Commitment_

typedef ::prometheus_msgs::Commitment_<std::allocator<void> > Commitment;

typedef boost::shared_ptr< ::prometheus_msgs::Commitment > CommitmentPtr;
typedef boost::shared_ptr< ::prometheus_msgs::Commitment const> CommitmentConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::prometheus_msgs::Commitment_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::prometheus_msgs::Commitment_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::prometheus_msgs::Commitment_<ContainerAllocator1> & lhs, const ::prometheus_msgs::Commitment_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.uav_id == rhs.uav_id &&
    lhs.commitmentState == rhs.commitmentState &&
    lhs.sitePos == rhs.sitePos &&
    lhs.quality == rhs.quality;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::prometheus_msgs::Commitment_<ContainerAllocator1> & lhs, const ::prometheus_msgs::Commitment_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace prometheus_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::prometheus_msgs::Commitment_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::prometheus_msgs::Commitment_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::prometheus_msgs::Commitment_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::prometheus_msgs::Commitment_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::prometheus_msgs::Commitment_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::prometheus_msgs::Commitment_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::prometheus_msgs::Commitment_<ContainerAllocator> >
{
  static const char* value()
  {
    return "29a5733d98998434ae7ab271018dc948";
  }

  static const char* value(const ::prometheus_msgs::Commitment_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x29a5733d98998434ULL;
  static const uint64_t static_value2 = 0xae7ab271018dc948ULL;
};

template<class ContainerAllocator>
struct DataType< ::prometheus_msgs::Commitment_<ContainerAllocator> >
{
  static const char* value()
  {
    return "prometheus_msgs/Commitment";
  }

  static const char* value(const ::prometheus_msgs::Commitment_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::prometheus_msgs::Commitment_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"## XXX implemented\n"
"int32 uav_id ## 无人机id\n"
"\n"
"int32 commitmentState ## 无人机commitment_state\n"
"float32[3] sitePos ## L_m\n"
"float32 quality ## q_m\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::prometheus_msgs::Commitment_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::prometheus_msgs::Commitment_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.uav_id);
      stream.next(m.commitmentState);
      stream.next(m.sitePos);
      stream.next(m.quality);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Commitment_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::prometheus_msgs::Commitment_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::prometheus_msgs::Commitment_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "uav_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.uav_id);
    s << indent << "commitmentState: ";
    Printer<int32_t>::stream(s, indent + "  ", v.commitmentState);
    s << indent << "sitePos[]" << std::endl;
    for (size_t i = 0; i < v.sitePos.size(); ++i)
    {
      s << indent << "  sitePos[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.sitePos[i]);
    }
    s << indent << "quality: ";
    Printer<float>::stream(s, indent + "  ", v.quality);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PROMETHEUS_MSGS_MESSAGE_COMMITMENT_H
