// Generated by gencpp from file prometheus_msgs/Msg104.msg
// DO NOT EDIT!


#ifndef PROMETHEUS_MSGS_MESSAGE_MSG104_H
#define PROMETHEUS_MSGS_MESSAGE_MSG104_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace prometheus_msgs
{
template <class ContainerAllocator>
struct Msg104_
{
  typedef Msg104_<ContainerAllocator> Type;

  Msg104_()
    : header()
    , command(0)  {
    }
  Msg104_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , command(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _command_type;
  _command_type command;





  typedef boost::shared_ptr< ::prometheus_msgs::Msg104_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::prometheus_msgs::Msg104_<ContainerAllocator> const> ConstPtr;

}; // struct Msg104_

typedef ::prometheus_msgs::Msg104_<std::allocator<void> > Msg104;

typedef boost::shared_ptr< ::prometheus_msgs::Msg104 > Msg104Ptr;
typedef boost::shared_ptr< ::prometheus_msgs::Msg104 const> Msg104ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::prometheus_msgs::Msg104_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::prometheus_msgs::Msg104_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::prometheus_msgs::Msg104_<ContainerAllocator1> & lhs, const ::prometheus_msgs::Msg104_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.command == rhs.command;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::prometheus_msgs::Msg104_<ContainerAllocator1> & lhs, const ::prometheus_msgs::Msg104_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace prometheus_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::prometheus_msgs::Msg104_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::prometheus_msgs::Msg104_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::prometheus_msgs::Msg104_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::prometheus_msgs::Msg104_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::prometheus_msgs::Msg104_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::prometheus_msgs::Msg104_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::prometheus_msgs::Msg104_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ed09803ffb3a5f32a556defaac4cdf06";
  }

  static const char* value(const ::prometheus_msgs::Msg104_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xed09803ffb3a5f32ULL;
  static const uint64_t static_value2 = 0xa556defaac4cdf06ULL;
};

template<class ContainerAllocator>
struct DataType< ::prometheus_msgs::Msg104_<ContainerAllocator> >
{
  static const char* value()
  {
    return "prometheus_msgs/Msg104";
  }

  static const char* value(const ::prometheus_msgs::Msg104_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::prometheus_msgs::Msg104_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"uint8 command\n"
"\n"
"\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::prometheus_msgs::Msg104_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::prometheus_msgs::Msg104_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.command);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Msg104_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::prometheus_msgs::Msg104_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::prometheus_msgs::Msg104_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "command: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.command);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PROMETHEUS_MSGS_MESSAGE_MSG104_H
