// Generated by gencpp from file prometheus_msgs/SwarmCommand.msg
// DO NOT EDIT!


#ifndef PROMETHEUS_MSGS_MESSAGE_SWARMCOMMAND_H
#define PROMETHEUS_MSGS_MESSAGE_SWARMCOMMAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace prometheus_msgs
{
template <class ContainerAllocator>
struct SwarmCommand_
{
  typedef SwarmCommand_<ContainerAllocator> Type;

  SwarmCommand_()
    : header()
    , Command_ID(0)
    , source()
    , All_Offboard_Control_Flg(false)
    , Mode(0)
    , swarm_shape(0)
    , Move_mode(0)
    , swarm_size(0.0)
    , position_ref()
    , velocity_ref()
    , acceleration_ref()
    , yaw_ref(0.0)
    , yaw_rate_ref(0.0)  {
      position_ref.assign(0.0);

      velocity_ref.assign(0.0);

      acceleration_ref.assign(0.0);
  }
  SwarmCommand_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , Command_ID(0)
    , source(_alloc)
    , All_Offboard_Control_Flg(false)
    , Mode(0)
    , swarm_shape(0)
    , Move_mode(0)
    , swarm_size(0.0)
    , position_ref()
    , velocity_ref()
    , acceleration_ref()
    , yaw_ref(0.0)
    , yaw_rate_ref(0.0)  {
  (void)_alloc;
      position_ref.assign(0.0);

      velocity_ref.assign(0.0);

      acceleration_ref.assign(0.0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _Command_ID_type;
  _Command_ID_type Command_ID;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _source_type;
  _source_type source;

   typedef uint8_t _All_Offboard_Control_Flg_type;
  _All_Offboard_Control_Flg_type All_Offboard_Control_Flg;

   typedef uint8_t _Mode_type;
  _Mode_type Mode;

   typedef uint8_t _swarm_shape_type;
  _swarm_shape_type swarm_shape;

   typedef uint8_t _Move_mode_type;
  _Move_mode_type Move_mode;

   typedef float _swarm_size_type;
  _swarm_size_type swarm_size;

   typedef boost::array<float, 3>  _position_ref_type;
  _position_ref_type position_ref;

   typedef boost::array<float, 3>  _velocity_ref_type;
  _velocity_ref_type velocity_ref;

   typedef boost::array<float, 3>  _acceleration_ref_type;
  _acceleration_ref_type acceleration_ref;

   typedef float _yaw_ref_type;
  _yaw_ref_type yaw_ref;

   typedef float _yaw_rate_ref_type;
  _yaw_rate_ref_type yaw_rate_ref;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(Idle)
  #undef Idle
#endif
#if defined(_WIN32) && defined(Takeoff)
  #undef Takeoff
#endif
#if defined(_WIN32) && defined(Hold)
  #undef Hold
#endif
#if defined(_WIN32) && defined(Land)
  #undef Land
#endif
#if defined(_WIN32) && defined(Disarm)
  #undef Disarm
#endif
#if defined(_WIN32) && defined(Position_Control)
  #undef Position_Control
#endif
#if defined(_WIN32) && defined(Velocity_Control)
  #undef Velocity_Control
#endif
#if defined(_WIN32) && defined(Accel_Control)
  #undef Accel_Control
#endif
#if defined(_WIN32) && defined(Move)
  #undef Move
#endif
#if defined(_WIN32) && defined(User_Mode1)
  #undef User_Mode1
#endif
#if defined(_WIN32) && defined(One_column)
  #undef One_column
#endif
#if defined(_WIN32) && defined(Triangle)
  #undef Triangle
#endif
#if defined(_WIN32) && defined(Square)
  #undef Square
#endif
#if defined(_WIN32) && defined(Circular)
  #undef Circular
#endif
#if defined(_WIN32) && defined(XYZ_POS)
  #undef XYZ_POS
#endif
#if defined(_WIN32) && defined(XY_POS_Z_VEL)
  #undef XY_POS_Z_VEL
#endif
#if defined(_WIN32) && defined(XY_VEL_Z_POS)
  #undef XY_VEL_Z_POS
#endif
#if defined(_WIN32) && defined(XYZ_VEL)
  #undef XYZ_VEL
#endif
#if defined(_WIN32) && defined(XYZ_ACC)
  #undef XYZ_ACC
#endif
#if defined(_WIN32) && defined(TRAJECTORY)
  #undef TRAJECTORY
#endif
#if defined(_WIN32) && defined(XYZ_POS_BODY)
  #undef XYZ_POS_BODY
#endif
#if defined(_WIN32) && defined(XYZ_VEL_BODY)
  #undef XYZ_VEL_BODY
#endif
#if defined(_WIN32) && defined(XY_VEL_Z_POS_BODY)
  #undef XY_VEL_Z_POS_BODY
#endif

  enum {
    Idle = 0u,
    Takeoff = 1u,
    Hold = 2u,
    Land = 3u,
    Disarm = 4u,
    Position_Control = 5u,
    Velocity_Control = 6u,
    Accel_Control = 7u,
    Move = 8u,
    User_Mode1 = 9u,
    One_column = 0u,
    Triangle = 1u,
    Square = 2u,
    Circular = 3u,
    XYZ_POS = 0u,
    XY_POS_Z_VEL = 1u,
    XY_VEL_Z_POS = 2u,
    XYZ_VEL = 3u,
    XYZ_ACC = 4u,
    TRAJECTORY = 5u,
    XYZ_POS_BODY = 6u,
    XYZ_VEL_BODY = 7u,
    XY_VEL_Z_POS_BODY = 8u,
  };


  typedef boost::shared_ptr< ::prometheus_msgs::SwarmCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::prometheus_msgs::SwarmCommand_<ContainerAllocator> const> ConstPtr;

}; // struct SwarmCommand_

typedef ::prometheus_msgs::SwarmCommand_<std::allocator<void> > SwarmCommand;

typedef boost::shared_ptr< ::prometheus_msgs::SwarmCommand > SwarmCommandPtr;
typedef boost::shared_ptr< ::prometheus_msgs::SwarmCommand const> SwarmCommandConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::prometheus_msgs::SwarmCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::prometheus_msgs::SwarmCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::prometheus_msgs::SwarmCommand_<ContainerAllocator1> & lhs, const ::prometheus_msgs::SwarmCommand_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.Command_ID == rhs.Command_ID &&
    lhs.source == rhs.source &&
    lhs.All_Offboard_Control_Flg == rhs.All_Offboard_Control_Flg &&
    lhs.Mode == rhs.Mode &&
    lhs.swarm_shape == rhs.swarm_shape &&
    lhs.Move_mode == rhs.Move_mode &&
    lhs.swarm_size == rhs.swarm_size &&
    lhs.position_ref == rhs.position_ref &&
    lhs.velocity_ref == rhs.velocity_ref &&
    lhs.acceleration_ref == rhs.acceleration_ref &&
    lhs.yaw_ref == rhs.yaw_ref &&
    lhs.yaw_rate_ref == rhs.yaw_rate_ref;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::prometheus_msgs::SwarmCommand_<ContainerAllocator1> & lhs, const ::prometheus_msgs::SwarmCommand_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace prometheus_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::prometheus_msgs::SwarmCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::prometheus_msgs::SwarmCommand_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::prometheus_msgs::SwarmCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::prometheus_msgs::SwarmCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::prometheus_msgs::SwarmCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::prometheus_msgs::SwarmCommand_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::prometheus_msgs::SwarmCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bcde920b51ed64de69265b8e65e78836";
  }

  static const char* value(const ::prometheus_msgs::SwarmCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbcde920b51ed64deULL;
  static const uint64_t static_value2 = 0x69265b8e65e78836ULL;
};

template<class ContainerAllocator>
struct DataType< ::prometheus_msgs::SwarmCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "prometheus_msgs/SwarmCommand";
  }

  static const char* value(const ::prometheus_msgs::SwarmCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::prometheus_msgs::SwarmCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"## 控制命令的编号 防止接收到错误命令， 编号应该逐次递加\n"
"uint32 Command_ID\n"
"\n"
"## 消息来源\n"
"string source\n"
"\n"
"##控制所有活动切换为offboard的flg\n"
"bool All_Offboard_Control_Flg\n"
"\n"
"## 控制命令的模式 \n"
"uint8 Mode\n"
"# enum Mode 控制模式枚举\n"
"uint8 Idle=0\n"
"uint8 Takeoff=1\n"
"uint8 Hold=2\n"
"uint8 Land=3\n"
"uint8 Disarm=4\n"
"uint8 Position_Control=5\n"
"uint8 Velocity_Control=6\n"
"uint8 Accel_Control=7\n"
"uint8 Move=8\n"
"uint8 User_Mode1=9\n"
"\n"
"## 控制参考量 \n"
"uint8 swarm_shape\n"
"\n"
"uint8 One_column=0\n"
"uint8 Triangle=1\n"
"uint8 Square=2\n"
"uint8 Circular=3\n"
"\n"
"## 默认为 XYZ位置追踪模式 （sub_mode = 0）； 速度追踪启用时，控制器不考虑位置参考量及位置状态反馈\n"
"uint8 Move_mode\n"
"\n"
"uint8 XYZ_POS      = 0  ##0b00\n"
"uint8 XY_POS_Z_VEL = 1  ##0b01\n"
"uint8 XY_VEL_Z_POS = 2  ##0b10\n"
"uint8 XYZ_VEL = 3       ##0b11\n"
"uint8 XYZ_ACC = 4\n"
"uint8 TRAJECTORY   = 5 \n"
"uint8 XYZ_POS_BODY = 6  \n"
"uint8 XYZ_VEL_BODY = 7\n"
"uint8 XY_VEL_Z_POS_BODY = 8\n"
"\n"
"float32 swarm_size\n"
"\n"
"float32[3] position_ref          ## [m]\n"
"float32[3] velocity_ref          ## [m]\n"
"float32[3] acceleration_ref\n"
"float32 yaw_ref                  ## [rad]\n"
"float32 yaw_rate_ref\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::prometheus_msgs::SwarmCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::prometheus_msgs::SwarmCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.Command_ID);
      stream.next(m.source);
      stream.next(m.All_Offboard_Control_Flg);
      stream.next(m.Mode);
      stream.next(m.swarm_shape);
      stream.next(m.Move_mode);
      stream.next(m.swarm_size);
      stream.next(m.position_ref);
      stream.next(m.velocity_ref);
      stream.next(m.acceleration_ref);
      stream.next(m.yaw_ref);
      stream.next(m.yaw_rate_ref);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SwarmCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::prometheus_msgs::SwarmCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::prometheus_msgs::SwarmCommand_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "Command_ID: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.Command_ID);
    s << indent << "source: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.source);
    s << indent << "All_Offboard_Control_Flg: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.All_Offboard_Control_Flg);
    s << indent << "Mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Mode);
    s << indent << "swarm_shape: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.swarm_shape);
    s << indent << "Move_mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Move_mode);
    s << indent << "swarm_size: ";
    Printer<float>::stream(s, indent + "  ", v.swarm_size);
    s << indent << "position_ref[]" << std::endl;
    for (size_t i = 0; i < v.position_ref.size(); ++i)
    {
      s << indent << "  position_ref[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.position_ref[i]);
    }
    s << indent << "velocity_ref[]" << std::endl;
    for (size_t i = 0; i < v.velocity_ref.size(); ++i)
    {
      s << indent << "  velocity_ref[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.velocity_ref[i]);
    }
    s << indent << "acceleration_ref[]" << std::endl;
    for (size_t i = 0; i < v.acceleration_ref.size(); ++i)
    {
      s << indent << "  acceleration_ref[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.acceleration_ref[i]);
    }
    s << indent << "yaw_ref: ";
    Printer<float>::stream(s, indent + "  ", v.yaw_ref);
    s << indent << "yaw_rate_ref: ";
    Printer<float>::stream(s, indent + "  ", v.yaw_rate_ref);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PROMETHEUS_MSGS_MESSAGE_SWARMCOMMAND_H
