(cl:in-package prometheus_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          CONNECTED-VAL
          CONNECTED
          ARMED-VAL
          ARMED
          LANDED-VAL
          LANDED
          MODE-VAL
          MODE
          ODOM_VALID-VAL
          ODOM_VALID
          TIME_FROM_START-VAL
          TIME_FROM_START
          POSITION-VAL
          POSITION
          REL_ALT-VAL
          REL_ALT
          VELOCITY-VAL
          VELOCITY
          ATTITUDE-VAL
          ATTITUDE
          ATTITUDE_Q-VAL
          ATTITUDE_Q
          ATTITUDE_RATE-VAL
          ATTITUDE_RATE
          BATTERY_STATE-VAL
          BATTERY_STATE
          UAV_ID-VAL
          UAV_ID
          OPINIONVALIDFLG-VAL
          OPINIONVALIDFLG
          COMMITMENTSTATE-VAL
          COMMITMENTSTATE
          VOTEVALIDFLG-VAL
          VOTEVALIDFLG
          SITEPOS-VAL
          SITEPOS
          QUALITY-VAL
          QUALITY
))